# Pytorch_Basic (3)        

- Autograd
   - torch.Tensor
   - 만약 **.requires_grad** 속성을 True로 설정하면, 그 tensor에서 이뤄진 모든 연산들을 추적(track) 한다.


In [2]:
import torch
import torch.nn as no
import torch.nn.functional as F

In [14]:
# requires_grad ,  기존 Tensor의 값을 바꿔버림(in-place)
# 활용하기 위해서는 함수 내 requires_grad를 True로 설정한다.

x = torch.ones(2, 2, requires_grad=True)  # 2x2 행렬 선언
print(x) # Tensor로 계산한 Function을 참조

x_ = torch.ones(2, 2, requires_grad=False) # grad = False인 경우,,,

y = x + 2
print(y) # grad_fn=<AddBackward0> ~ 연산의 결과로 생성, 생성된 함수를 참조하는 속성

with torch.no_grad() : # no_grad 옵션으로 추적 종료
    z = y * y * 3
    print(z)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]])
